ANALYSIS_SLIDING_WINDOW_MODULE_NAME := analysis/sliding_window
SUBMODULES := 

ANALYSIS_SLIDING_WINDOW_SUBMODULES := $(foreach weight,$(SLIDING_WINDOW_WEIGHTS),$(addprefix $(ANALYSIS_SLIDING_WINDOW_MODULE_NAME)/window_,$(weight)))
$(ANALYSIS_SLIDING_WINDOW_MODULE_NAME): $(ANALYSIS_SLIDING_WINDOW_SUBMODULES)

define analysis-sliding-makefiles
MODULE_NAME := $(1)
include $(COMMON_ANALYSIS_MAKEFILE)
endef

$(foreach m,$(ANALYSIS_SLIDING_WINDOW_SUBMODULES),$(eval $(call analysis-sliding-makefiles,$(m))))

$(ANALYSIS_SLIDING_WINDOW_MODULE_NAME)/clean:
	rm -rf $(ANALYSIS_SLIDING_WINDOW_SUBMODULES)
